# This workflow will do a clean installation of node dependencies,
# cache/restore them, build the source code, run tests, and deploy to
# GitHub Pages
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Upload artifact
        uses: actions/upload-artifact@v4
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
        
